### ISSUE TITLE
Need guidance on implementing grpc

### ISSUE THREAD

**Issue by abhinavzspace** [xuwei-k/grpc-scala-sample#2]
@xuwei-k and @tayama0324 can you show us a few hints on where to look for the code for implementing grpc on our project. Thanks a lot for this excellent work.

**Comment by xuwei-k** [comment]
This is just translated codes from gRPC java examples, not tutorial project/documentations.
The issue tracker is not a support system.

**Comment by abhinavzspace** [comment]
I am sorry.
