### ISSUE TITLE
Unable to build channel

### ISSUE THREAD

**Issue by gorros** [xuwei-k/grpc-scala-sample#8]
I am getting following error 
```
Error:(20, 87) value build is not a member of ?0
        val channel = ManagedChannelBuilder.forAddress(host, port).usePlaintext(true).build
```
for this [line](https://github.com/xuwei-k/grpc-scala-sample/blob/358b8bd020a02d4292debf62f5037253b8745c82/grpc-scala/src/main/scala/io/grpc/examples/helloworld/HelloWorldClient.scala#L46)

**Comment by xuwei-k** [comment]
I could not reproduce your error. I just updated scalapb 0.6.0 and grpc-java 1.4.0 and then success travis-ci job.
- https://github.com/xuwei-k/grpc-scala-sample/commit/4c4374605088dde8fb8c42772adf00fccd9cd5d5
- https://travis-ci.org/xuwei-k/grpc-scala-sample/builds/248790292
